### ISSUE TITLE
optimized entity's invisible when using shaders

### ISSUE THREAD

**Issue by syelents** [Engine-Room/Flywheel#115]
### Describe the Bug

When using the [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) mod with shaders enabled, certain entities become invisible. Specifically, the ones mentioned that have been optimized (chests and bells).
I have looked for a way to disable the optimizations, the only thing I could find in the config was "experimental rendering". Turning this off had no change. I am unsure if this is the optimized rendering mentioned on the curseforge page.

### Reproduction Steps

1. install Oculus and Flywheel
2. enable any shader

### Expected Result

Chests and bells should be visible when using shaders.

### Screenshots and Videos

![2022-03-04_18 20 15](https://user-images.githubusercontent.com/54427152/156854994-9540ac67-3420-46f6-a728-d198e4f031c2.png)
![2022-03-04_18 20 03](https://user-images.githubusercontent.com/54427152/156854996-d3d8b312-a021-4cef-b564-0270f2f33c6e.png)

### Operating System

Windows 11

### What is your GPU?

Nvidia RTX 2070

### Mod Version

0.6.0

### Minecraft Version

1.18.1

### Forge Version

39.1.2

**Comment by Jozufozu** [comment]
`/flywheel backend off` should do it.

Flywheel forge doesn't expect any shader mod other than optifine to exist.

**Comment by syelents** [comment]
Works! Thanks for the fast reply!

**Comment by SmokePuddingEveryday** [comment]
Is anyone aware of some kind of fix for the 1.16.5 variant of this issue? Chests and such don't render at all using Flywheel + Oculus, regardless of shaders being enabled or disabled.

Using `/flywheel backend off` causes all block entities to render completely invisible, and using `/flywheel backend on` causes all block entities to render completely black.

Screenshots:
[Flywheel Backend Disabled](https://i.imgur.com/RSDLLou.png)
[Flywheel Backend Enabled](https://i.imgur.com/nLzv4uU.png)

Video: https://streamable.com/lqu0vo

Thank you, and apologies if this is the wrong place to post this.

**Comment by ShibeTemple** [comment]
> 

The guy who ported Iris to forge (oculus dev) is unaware of what is causing the issue. The Iris dev team will not care or try to fix it as their mod is only on Fabric, so we are kind of only here hoping that @Jozufozu can help with something.... I am praying tbh.

**Comment by EvergreenSystems** [comment]
This has been fixed, at least with create-added blocks, on oculus's end in 1.18.2

https://www.curseforge.com/minecraft/mc-mods/oculus/files/3770744

**Comment by inverspe** [comment]
> This has been fixed, at least with create-added blocks, on oculus's end in 1.18.2
> 
> https://www.curseforge.com/minecraft/mc-mods/oculus/files/3770744

nope, I tested it chest is still invisible and other stuff as well.

**Comment by SmokePuddingEveryday** [comment]
Also still present on the 1.16.5 version as of Oculus 1.2.5. Tested with Supplementary and SEUS Renewed Shaders.

**Comment by Jozufozu** [comment]
Fixed in latest 1.18.2 flywheel

**Comment by LiVeenMusic** [comment]
what about 1.16.5 though.. :/ damnit, been trying for a month to fix this
