### ISSUE TITLE
Incompatibility with Oculus mod by Asek3 (Iris port)

### ISSUE THREAD

**Issue by ShibeTemple** [Engine-Room/Flywheel#117]
### Describe the Bug

Oculus is a mod by Asek3, which is a Forge port of Iris. This mod is incompatible with the Flywheel engine/Create and crashes whenever a Create block is placed. This issue has been reported to [Asek3](https://github.com/Asek3) and they insist it is an issue with Flywheel. See [Oculus Issue Asek3/Iris#24](Asek3/Iris#24) and [Oculus Issue Asek3/Iris#26](Asek3/Iris#26). Additionally, `/flywheel backend off` does not solve or prevent the issue.

### Reproduction Steps

1. Install Rubidium mod (Sodium port by [Asek3](https://github.com/Asek3)), Iris mod by [Asek3](https://github.com/Asek3), Flywheel, and Create.
2. Open world
3. Place Create block. (i.e. cogwheel)
4. Game crash. World now un-joinable.
...

### Expected Result

Iris allows for the rendering of Flywheel/Create objects. 

### Crash Report or Log

https://gist.github.com/ShibeTemple/66e7192b4cbd86e950db490ecbaa4128

### Operating System

Windows 10

### What is your GPU?

NVIDIA RTX 3090

### Mod Version

0.6.0

### Minecraft Version

1.18.1

### Forge Version

39.0.79

### Other Mods

Please see gist.

**Comment by mekrod** [comment]
it now works, with the new update, however, the flywheel instances are invisible.

**Comment by ShibeTemple** [comment]
Can confirm @mekrod... hopefully, this gets fixed! :)

**Comment by EvergreenSystems** [comment]
Can confirm that flywheel will still cause a crash if the /flywheel backend command is used in-game and set to anything other than off

**Comment by ShibeTemple** [comment]
I hope this gets fixed.

**Comment by dr3amnightmare** [comment]
Also having issues on 1.16.5 with this

**Comment by Gunseeker** [comment]
I'm also having this issue in the 1.18.2 version.

**Comment by EvergreenSystems** [comment]
This has been fixed in 1.18.2 on Oculus's end

https://www.curseforge.com/minecraft/mc-mods/oculus/files/3770744

**Comment by botafi** [comment]
> This has been fixed in 1.18.2 on Oculus's end
> 
> https://www.curseforge.com/minecraft/mc-mods/oculus/files/3770744

this version did not help still crashes on create blocks render

**Comment by Jozufozu** [comment]
Should be fixed in the latest version
